### ISSUE TITLE
Pointer scan for this address

### ISSUE THREAD

**Issue by eXskill** [Metick/CheatEngine-DMA#14]
Great project!
For a complete gentleman's set, the "Pointer scan for this address" functionality is required, but it does not work yet.
Are you planning to add this feature?

**Comment by Metick** [comment]
It is planned, I just haven't started on it yet.

**Comment by kamuran21** [comment]
I tried to resolve this part, on my fork but i couldn't. I couldn't find the hook which i should to work on it. I tried to inject kernel dll to DMA target via DMA but it crashed the target memory, each time. I hope Metick will need it ASAP, or can resolve this for us ^^

**Comment by kaijia2022** [comment]
I resolved pointer scanning!! not within Metick's plugin though.  I haven't tried to debug Metick's implementation but looking at the source code, I am sure this is one of the problems (for debugging a 64-bit process):

![hk_openprocess](https://github.com/user-attachments/assets/f2e485ca-8072-428d-8356-d2c49c705db0)

Since the `hk_openprocess` returns an invalid handle, the call to `isWow64bitProcess` below in the `newkernelhandler` unit would return `False`. 

![iswow64bit](https://github.com/user-attachments/assets/4f3b6e52-bf75-477a-8c55-f47f871aa8d5)

Which would set `processhandler.is64bit` to false and mess up pointer map generation by passing the 32bit stop address `$0xFFFFFFFF` to `stop` in `processhandler` unit.

![processhandlerunit](https://github.com/user-attachments/assets/608c133a-43a0-4ec3-b2dc-00468dcc4c01)

This would further mess up the pointer map and pointer scanning in `pointervaluelist` unit.

However, since the current version of ce plugin sdk does not export the `isWow64process` function, I ended up solving this by adding it to the exported functions in the ce source code. If anyone has a better solution around this, please let me know.

[Here](https://github.com/kaijia2022/Cheat-Engine-DMA-Plugin) is the link to my plugin.
